# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0695b1f913542225ba55ea2fdefd7b8f1fae8e33e0bb1db5885a32c8ae40c9d89cb2713519058492a3ff183cb0362ba84fccde59899e90b4082f62599dce6b2b

test:
  secret_key_base: 7cc9930730cc593559e149962acd6c2331e831af39dfba8eb2be816016446f855c40d3a3ea3bc83b0d3ebbb03bc8a31bc41ea241661d4d3674f208659ce2d313

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
